export const CONNECT_WALLET = 'CONNECT_WALLET';
export const CONNECT_GUEST = 'CONNECT_GUEST';
export const DISCONNECT_WALLET = 'DISCONNECT_WALLET';
export const LOAD_CONTRACT = 'LOAD_CONTRACT';
export const MONITOR_ACCOUNT_CHANGED = 'MONITOR_ACCOUNT_CHANGED';
export const MONITOR_DISCONNECT = 'MONITOR_DISCONNECT';
export const FETCH_ALL_TOURNAMENTS = 'FETCH_ALL_TOURNAMENTS';
export const FETCH_ALL_PLAYERS = 'FETCH_ALL_PLAYERS';
export const FETCH_JOINED_TOURNAMENTS = 'FETCH_JOINED_TOURNAMENTS';
export const FETCH_ADMINS = 'FETCH_ADMINS';
export const FETCH_USERS = 'FETCH_USERS';
export const CURRENT_TOURNAMENT = 'CURRENT_TOURNAMENT';
export const FETCH_CONTRACT_TOKENS = 'FETCH_CONTRACT_TOKENS';
export const FETCH_CONTRACT_ETH = 'FETCH_CONTRACT_ETH';
export const CHECK_ADMIN= 'CHECK_ADMIN';
export const FETCH_TOKEN_PRICE = 'FETCH_TOKEN_PRICE'

export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';

export const UPDATE_BOARD = 'UPDATE_BOARD';
export const UPDATE_CURRENT_ATTEMPT = 'UPDATE_CURRENT_ATTEMPT';
export const GENERATE_WORD_SET = 'GENERATE_WORD_SET';
export const UPDATE_WORD_SET = 'UPDATE_WORD_SET';
export const UPDATE_DISABLED_LETTERS = 'UPDATE_DISABLED_LETTERS';
export const UPDATE_GAME_OVER = 'UPDATE_GAME_OVER';
export const UPDATE_CORRECT_WORD = 'UPDATE_CORRECT_WORD';
export const RESET_BOARD = 'RESET_BOARD';

