export const CONNECT_WALLET = 'CONNECT_WALLET';
export const CONNECT_GUEST = 'CONNECT_GUEST';
export const DISCONNECT_WALLET = 'DISCONNECT_WALLET';
export const LOAD_CONTRACT = 'LOAD_CONTRACT';
export const MONITOR_ACCOUNT_CHANGED = 'MONITOR_ACCOUNT_CHANGED';
export const MONITOR_DISCONNECT = 'MONITOR_DISCONNECT';
export const FETCH_ALL_TOURNAMENTS = 'FETCH_ALL_TOURNAMENTS';
export const FETCH_ALL_PLAYERS = 'FETCH_ALL_PLAYERS';
export const FETCH_JOINED_TOURNAMENTS = 'FETCH_JOINED_TOURNAMENTS';
export const FETCH_ADMINS = 'FETCH_ADMINS';

export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';

